# generated by google gemini
# convert input.mp4 to output.mp4 to display on black-white screen

import cv2
import numpy as np
import time

def get_bayer_matrix():
    """生成 4x4 Bayer 矩阵用于有序抖动"""
    bayer_4x4 = np.array([
        [ 0,  8,  2, 10],
        [12,  4, 14,  6],
        [ 3, 11,  1,  9],
        [15,  7, 13,  5]
    ])
    # 将 0-15 映射到 0-255 阈值
    return (bayer_4x4 + 0.5) / 16.0 * 255.0

def apply_dither(gray_frame, method='bayer'):
    """对单通道灰度图像应用指定的 Dither 算法"""
    if method == 'bayer':
        # 有序抖动 (Ordered Dither) - 速度极快，适合视频
        h, w = gray_frame.shape
        bayer_matrix = get_bayer_matrix()
        # 将 4x4 矩阵平铺(tile)到与视频帧相同的尺寸
        threshold_map = np.tile(bayer_matrix, (h // 4 + 1, w // 4 + 1))[:h, :w]
        return np.where(gray_frame > threshold_map, 255, 0).astype(np.uint8)

    elif method == 'random':
        # 随机抖动 (Random Dither) - 速度极快，产生噪点感
        noise = np.random.randint(0, 256, gray_frame.shape)
        return np.where(gray_frame > noise, 255, 0).astype(np.uint8)

    elif method == 'floyd-steinberg':
        # 误差扩散抖动 (Floyd-Steinberg) - 画质最好但 Python 单线程极其缓慢！
        img = gray_frame.astype(float)
        h, w = img.shape
        for y in range(h):
            for x in range(w):
                old_pixel = img[y, x]
                new_pixel = 255 if old_pixel > 127 else 0
                img[y, x] = new_pixel
                quant_error = old_pixel - new_pixel
                
                # 分配误差到相邻像素
                if x < w - 1:
                    img[y, x + 1] += quant_error * 7 / 16
                if y < h - 1:
                    if x > 0:
                        img[y + 1, x - 1] += quant_error * 3 / 16
                    img[y + 1, x] += quant_error * 5 / 16
                    if x < w - 1:
                        img[y + 1, x + 1] += quant_error * 1 / 16
        
        return np.clip(img, 0, 255).astype(np.uint8)
    
    else:
        # 默认回退为普通的 127 阈值二值化 (非 Dither)
        _, binary = cv2.threshold(gray_frame, 127, 255, cv2.THRESH_BINARY)
        return binary

def crop_and_resize(frame, target_size):
    """根据指定长宽裁切较长的边，并缩放"""
    target_w, target_h = target_size
    h, w = frame.shape[:2]
    
    src_ratio = w / h
    target_ratio = target_w / target_h
    
    if abs(src_ratio - target_ratio) > 1e-5:
        if src_ratio > target_ratio:
            # 原图更宽，需要裁切掉左右两边
            new_w = int(h * target_ratio)
            start_x = (w - new_w) // 2
            frame = frame[:, start_x:start_x + new_w]
        else:
            # 原图更高，需要裁切掉上下两边
            new_h = int(w / target_ratio)
            start_y = (h - new_h) // 2
            frame = frame[start_y:start_y + new_h, :]
            
    # 裁切后进行等比缩放
    return cv2.resize(frame, (target_w, target_h), interpolation=cv2.INTER_AREA)

def process_video(input_path, output_path, target_size, dither_method='bayer'):
    """主处理函数"""
    cap = cv2.VideoCapture(input_path)
    if not cap.isOpened():
        print(f"错误: 无法打开视频文件 {input_path}")
        return

    # 获取原视频帧率和总帧数用于进度显示
    fps = cap.get(cv2.CAP_PROP_FPS)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    target_w, target_h = target_size

    # 设置 VideoWriter。由于是二值化灰度图，isColor 设置为 False
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, fps, (target_w, target_h), isColor=False)

    print(f"开始处理视频: {input_path}")
    print(f"目标尺寸: {target_w}x{target_h}, Dither 算法: {dither_method}")
    
    frame_count = 0
    start_time = time.time()

    while True:
        ret, frame = cap.read()
        if not ret:
            break
            
        # 1. 智能裁切与缩放
        resized_frame = crop_and_resize(frame, target_size)
        
        # 2. 转换为灰度图
        gray_frame = cv2.cvtColor(resized_frame, cv2.COLOR_BGR2GRAY)
        
        # 3. 应用 Dither 算法得到二值图
        dithered_frame = apply_dither(gray_frame, method=dither_method)
        
        # 4. 写入输出视频
        out.write(dithered_frame)
        
        frame_count += 1
        if frame_count % 30 == 0:
            print(f"进度: {frame_count}/{total_frames} 帧...")

    cap.release()
    out.release()
    print(f"处理完成！耗时: {time.time() - start_time:.2f} 秒. 输出文件: {output_path}")

# ================= 使用示例 =================
if __name__ == "__main__":
    # 输入文件路径、输出文件路径
    input_mp4 = "input.mp4"
    output_mp4 = "output.mp4" 

    # 目标长宽 (宽, 高)
    target_size = (128, 64)   
    
    # 支持的算法: 'bayer', 'random', 'floyd-steinberg'
    algorithm = 'floyd-steinberg'
    
    process_video(input_mp4, output_mp4, target_size, dither_method=algorithm)
