# NOTE download unifont hex file from https://unifoundry.com/unifont/index.html
# under section Font Downloads - Specialized versions - HEX
# extra the hex file and put it here

UNIFONT_HEX_FILE = 'unifont-17.0.04.hex'


def load_unifont():
    all_chars = {}
    with open(UNIFONT_HEX_FILE, 'r') as f:
        for line in f:
            code_str, data_str = line.split(':', 1)
            code_bytes = bytes.fromhex(code_str)
            data_bytes = bytes.fromhex(data_str)
            n = code_bytes[0] << 8 | code_bytes[1]
            all_chars[n] = data_bytes
    return all_chars


ALL_CHARS = load_unifont()


def get_char(n):
    if n in ALL_CHARS:
        return ALL_CHARS[n]
    return ALL_CHARS[0]


def dump_dict(d, f):
    f.write('# AUTO GENERATED by misc/scripts/extract_unifont.py\n')
    f.write('\n')

    f.write('ALL_CHARS = {\n')
    for k, v in d.items():
        line = '    {!r}: {!r},\n'.format(k, v)
        f.write(line)
    f.write('}\n')


if __name__ == '__main__':
    output_dict = {}
    for i in range(ord(' '), 127):
        data = get_char(i)
        output_dict[i] = data
        if len(data) != 16:
            print(i)

    with open('../../src/font_ascii_8x16.py', 'w') as f:
        dump_dict(output_dict, f)        
